CREATE TABLE [dbo].[BTRADE_OrderItem]
(
    OrderId VARCHAR(26) NOT NULL CONSTRAINT DF_BTRADE_OrderItem_OrderId DEFAULT(''),
    NoUrut INT NOT NULL CONSTRAINT DF_BTRADE_OrderItem_NoUrut DEFAULT(0),
    BrgId VARCHAR(6) NOT NULL CONSTRAINT DF_BTRADE_OrderItem_BrgId DEFAULT(''),
    BrgCode VARCHAR(20) NOT NULL CONSTRAINT DF_BTRADE_OrderItem_BrgCode DEFAULT(''),
    BrgName VARCHAR(60) NOT NULL CONSTRAINT DF_BTRADE_OrderItem_BrgName DEFAULT(''),
    KategoriName VARCHAR(30) NOT NULL CONSTRAINT DF_BTRADE_OrderItem_KategoriName DEFAULT(''),
    
    QtyBesar INT NOT NULL CONSTRAINT DF_BTRADE_OrderItem_QtyBesar DEFAULT(0),
    SatBesar VARCHAR(7) NOT NULL CONSTRAINT DF_BTRADE_OrderItem_SatBesar DEFAULT(''),
    QtyKecil INT NOT NULL CONSTRAINT DF_BTRADE_OrderItem_QtyKecil DEFAULT(0),
    SatKecil VARCHAR(7) NOT NULL CONSTRAINT DF_BTRADE_OrderItem_SatKecil DEFAULT(''),
    Konversi INT NOT NULL CONSTRAINT DF_BTRADE_OrderItem_Konversi DEFAULT(0),
    
    UnitPrice DECIMAL(18,0) NOT NULL CONSTRAINT DF_BTRADE_OrderItem_UnitPrice DEFAULT(0),
    LineTotal DECIMAL(18,0) NOT NULL CONSTRAINT DF_BTRADE_OrderItem_LineTotal DEFAULT(0),

    CONSTRAINT PK_BTRADE_OrderItem PRIMARY KEY CLUSTERED (OrderId ASC, NoUrut ASC)
)