CREATE TABLE BTRADE_Faktur(
    FakturId VARCHAR(12) NOT NULL CONSTRAINT DF_BTRADE_Faktur_FakturId DEFAULT(''),
    GlobalId VARCHAR(12) NOT NULL CONSTRAINT DF_BTRADE_Faktur_GlobalId DEFAULT(''),
    CustomerId VARCHAR(6) NOT NULL CONSTRAINT DF_BTRADE_Faktur_CustomerId DEFAULT(''),
    CustomerCode VARCHAR(10) NOT NULL CONSTRAINT DF_BTRADE_Faktur_CustomerCode DEFAULT(''),
    CustomerName VARCHAR(50) NOT NULL CONSTRAINT DF_BTRADE_Faktur_CustomerName DEFAULT(''),
    CustomerAddress VARCHAR(60) NOT NULL CONSTRAINT DF_BTRADE_Faktur_CustomerAddress DEFAULT(''),
    FakturDate VARCHAR(10) NOT NULL CONSTRAINT DF_BTRADE_Faktur_FakturDate DEFAULT(''),
    SalesId VARCHAR(5) NOT NULL CONSTRAINT DF_BTRADE_Faktur_SalesId DEFAULT(''),
    SalesName VARCHAR(50) NOT NULL CONSTRAINT DF_BTRADE_Faktur_SalesName DEFAULT(''),
    TotalAmount DECIMAL(18,0) NOT NULL CONSTRAINT DF_BTRADE_Faktur_TotalAmount DEFAULT(0),
    UserEmail VARCHAR(50) NOT NULL CONSTRAINT DF_BTRADE_Faktur_UserEmail DEFAULT(''),
    StatusSync VARCHAR(1) NOT NULL CONSTRAINT DF_BTRADE_Faktur_StatusSync DEFAULT('N'),
    
    CONSTRAINT PK_BTRADE_Faktur PRIMARY KEY CLUSTERED (GlobalId ASC)
)
