CREATE TABLE [dbo].[BTRADE_Brg]
(
	BrgId VARCHAR(6) NOT NULL CONSTRAINT DF_BTRADE_Brg_BrgId DEFAULT(''),
	BrgName VARCHAR(60) NOT NULL CONSTRAINT DF_BTRADE_Brg_BrgName DEFAULT(''),
	BrgCode VARCHAR(20) NOT NULL CONSTRAINT DF_BTRADE_Brg_BrgCode DEFAULT(''),
	KategoriName VARCHAR(30) NOT NULL CONSTRAINT DF_BTRADE_Brg_KategoriName DEFAULT(''),
	SatBesar VARCHAR(7) NOT NULL CONSTRAINT DF_BTRADE_Brg_SatBesar DEFAULT(''),
	SatKecil VARCHAR(7) NOT NULL CONSTRAINT DF_BTRADE_Brg_SatKecil DEFAULT(''),
	Konversi INT NOT NULL CONSTRAINT DF_BTRADE_Brg_Konversi DEFAULT(0),
	HrgSat DECIMAL(18,0) NOT NULL CONSTRAINT DF_BTRADE_Brg_HrgSat DEFAULT(0),
	Stok INT NOT NULL CONSTRAINT DF_BTRADE_Brg_Stok DEFAULT(0),

	CONSTRAINT PK_BTRADE_Brg PRIMARY KEY CLUSTERED (BrgId ASC)
)
