CREATE TABLE [dbo].[BTRADE_CheckIn]
(
    CheckInId VARCHAR(26) NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CheckInId DEFAULT(''),
    CheckInDate VARCHAR(10) NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CheckInDate DEFAULT(''),
    CheckInTime VARCHAR(8) NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CheckInTime DEFAULT(''),
    UserEmail VARCHAR(100) NOT NULL CONSTRAINT DF_BTRADE_CheckIn_UserEmail DEFAULT(''),
    CheckInLatitude FLOAT NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CheckInLatitude DEFAULT(0),
    CheckInLongitude FLOAT NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CheckInLongitude DEFAULT(0),
    Accuracy FLOAT NOT NULL CONSTRAINT DF_BTRADE_CheckIn_Accuracy DEFAULT(0),
    CustomerId VARCHAR(2) NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CustomerId DEFAULT(''),
    CustomerCode VARCHAR(20) NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CustomerCode DEFAULT(''),
    CustomerName VARCHAR(60) NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CustomerName DEFAULT(''),
    CustomerAddress VARCHAR(100) NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CustomerAddress DEFAULT(''),
    CustomerLatitude FLOAT NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CustomerLatitude DEFAULT(0),
    CustomerLongitude FLOAT NOT NULL CONSTRAINT DF_BTRADE_CheckIn_CustomerLongitude DEFAULT(0),
    StatusSync VARCHAR(20) NOT NULL CONSTRAINT DF_BTRADE_CheckIn_StatusSync DEFAULT(''),

    ServerId VARCHAR(5) NOT NULL CONSTRAINT DF_BTRADE_CheckIn_ServerId DEFAULT(''),

    CONSTRAINT PK_BTRADE_CheckIn PRIMARY KEY CLUSTERED (CheckInId ASC)
)