CREATE TABLE [dbo].[BTRADE_PackingOrderItem]
(
	PackingOrderId VARCHAR(26) NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_PackingOrderId DEFAULT (''),
	NoUrut INT NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_NoUrut DEFAULT (0),
	BrgId VARCHAR(6) NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_BrgId DEFAULT (''),
	BrgCode VARCHAR(20) NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_BrgCode DEFAULT (''),
	BrgName VARCHAR(100) NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_BrgName DEFAULT (''),
	KategoriName VARCHAR(60) NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_KategoriName DEFAULT (''),
	SupplierName VARCHAR(60) NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_SupplierName DEFAULT (''),
	QtyBesar INT NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_QtyBesar DEFAULT (0),
	SatBesar VARCHAR(10) NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_SatBesar DEFAULT (''),
	QtyKecil INT NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_QtyKecil DEFAULT (0),
	SatKecil VARCHAR(10) NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_SatKecil DEFAULT (''),
	DepoId VARCHAR(3) NOT NULL CONSTRAINT DF_BTRADE_PackingOrderItem_DepoId DEFAULT (''),

	CONSTRAINT PK_BTRADE_PackingOrderItem PRIMARY KEY CLUSTERED (PackingOrderId, NoUrut)
)
