CREATE TABLE [dbo].[BTRADE_Order]
(
    OrderId VARCHAR(26) NOT NULL CONSTRAINT DF_BTRADE_Order_OrderId DEFAULT(''),
    OrderLocalId VARCHAR(12) NOT NULL CONSTRAINT DF_BTRADE_Order_OrderLocalId DEFAULT(''),
    CustomerId VARCHAR(20) NOT NULL CONSTRAINT DF_BTRADE_Order_CustomerId DEFAULT(''),
    CustomerCode VARCHAR(20) NOT NULL CONSTRAINT DF_BTRADE_Order_CustomerCode DEFAULT(''),
    CustomerName VARCHAR(60) NOT NULL CONSTRAINT DF_BTRADE_Order_CustomerName DEFAULT(''),
    CustomerAddress VARCHAR(100) NOT NULL CONSTRAINT DF_BTRADE_Order_CustomerAddress DEFAULT(''),
    
    OrderDate VARCHAR(10) NOT NULL CONSTRAINT DF_BTRADE_Order_OrderDate DEFAULT('3000-01-01'),
    SalesId VARCHAR(20) NOT NULL CONSTRAINT DF_BTRADE_Order_SalesId DEFAULT(''),
    SalesName VARCHAR(60) NOT NULL CONSTRAINT DF_BTRADE_Order_SalesName DEFAULT(''),
    TotalAmount DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTRADE_Order_TotalAmount DEFAULT(0),
    
    UserEmail VARCHAR(100) NOT NULL CONSTRAINT DF_BTRADE_Order_UserEmail DEFAULT(''),
    StatusSync VARCHAR(20) NOT NULL CONSTRAINT DF_BTRADE_Order_StatusSync DEFAULT(''),
    FakturCode VARCHAR(20) NOT NULL CONSTRAINT DF_BTRADE_Order_FakturCode DEFAULT(''),

    ServerId VARCHAR(5) NOT NULL CONSTRAINT DF_BTRADE_Order_ServerId DEFAULT(''),

    CONSTRAINT PK_BTRADE_Order PRIMARY KEY CLUSTERED (OrderId ASC)
)